---
applied_at: '2023-01-09'
applies_to:
  - sdks
  - python
is_impactful: false
is_new_feature: false
release_source_url: 'https://github.com/box/box-python-sdk/releases/tag/v3.6.1'
collapse: true
is_index: false
category_id: changelog
subcategory_id: ''
id: 2023-01-09-box-python-sdk-v361-released
rank: null
total_steps: null
type: changelog
sibling_id: ''
parent_id: changelog
next_page_id: 2023-01-12-box-windows-sdk-v500-released
previous_page_id: 2023-01-05-box-node-sdk-v281-released
source_url: >-
  https://github.com/box/box-developer-changelog/blob/main/content/2023/01-09-box-python-sdk-v361-released.md
published_at: '2023-01-09'
fullyTranslated: true
---
# Box Python SDK `v3.6.1`のリリース

### バグ修正

* 接続リセットエラーが発生した場合に、CCGおよびJWT認証リクエストを再試行 ([#790][1]) ([`205997d`][2])、[#789][3]をクローズ

[1]: https://github.com/box/box-python-sdk/issues/790

[2]: https://github.com/box/box-python-sdk/commit/205997db9870395b9dd042854c4201338dcf925f

[3]: https://github.com/box/box-python-sdk/issues/789
